package com.example.domain;

public enum Status {

    SUCCESS, NO_NAME_MATCH, CANNOT_REMOVE_ITEM_NOT_EXIST, CANNOT_UPDATE_ITEM_NOT_EXIST,
    CANNOT_ADD_ITEM_ALREADY_EXIST, CANNOT_UPDATE_ITEM_INFO;
}
